### ISSUE TITLE
JuncTek_Batterymonitor Github + Battery Emulator 

### ISSUE THREAD

**Issue by dexterbot80** [pljakobs/JuncTek_Batterymonitor#1]
Hello good man, I accidentally discovered your library for Juncktec shunts on Github.
Some very good guys from Sweden have created a project with the help of which we can connect batteries recovered from electric cars to inverters. Do you think you could also integrate the Juncktec shunts so that the Fronius inverters can use the SOC and the voltage of the connected battery....?
I think you would bring a great green plus to the renewable energy storage community.
If you think you could add the functionality of your library to this code, please don't hesitate to contact me. dexterbot80@gmail.com
Sincerely, Daniel 
https://github.com/dalathegreat/Battery-Emulator/tree/v5.2.0
https://gitlab.com/pelle8/batteryemulator/-/blob/main/bms_juntek.py?ref_type=heads

**Comment by pljakobs** [comment]
Hi Daniel, 

not sure I can answer your questions. I am not affiliated with JuncTec and cannot, without knowing the project you mention, cannot make statements about the hardware applicability there. The library is available as-is, I am aware of one or two issues, but in general, it will work with the JuncTec battery monitors. 

if you check the technical parameters, all but one of the JuncTec devices are limited to 120V max, most EV batteries will be above that, the KL610 is specified up to 600V when externally powered - so that may be an option if 100A is enough (should be, 600Vx100A gets you 60kW of power max.) 

So again: if those JuncTec devices can be physically implemented in the solution, there is nothing stopping you from using this library to read their data. But I  can't help with the physical part. 

Also, since the Fronius devices have a documented json API, I'm not so sure what the benefit would be of doubling this on the battery side? Are there specific values you'd be looking for?

pj
